class_name = "0x"
class_room = "RN"
class_teacher = "Class Teacher"

title = "School Year"
subtitle = "Semester"

school_name = "School Name"
school_address = "School Address"

class_durations = [
    "07:55 - 08:40",
    "08:40 - 09:25",

    "09:45 - 10:30",
    "10:30 - 11:15",

    "11:35 - 12:20",
    "12:20 - 13:05",

    "13:40 - 14:25",
    "14:25 - 15:10",

    "15:20 - 16:05",
    "16:05 - 16:50"
]

[day_identifiers]
monday = "Mo"
tuesday = "Di"
wednesday = "Mi"
thursday = "Do"
friday = "Fr"
saturday = "Sa"
sunday = "So"

# MONDAY

[[monday]]
class = "Subject 1"
teacher = "Teacher 1"
room = "Room 1"

[[monday]]
class = "Subject 1"
teacher = "Teacher 1"
room = "Room 1"

[[monday]]
class = "Subject 2"
teacher = "Teacher 2"
room = "Room 2"

[[monday]]
class = "Subject 2"
teacher = "Teacher 2"
room = "Room 2"

[[monday]]
class = "Subject 3"
teacher = "Teacher 3"
room = "Room 3"

[[monday]]
class = "Subject 3"
teacher = "Teacher 3"
room = "Room 3"

# TUESDAY

[[tuesday]]
class = "Subject 4"
teacher = "Teacher 4"
room = "Room 4"

[[tuesday]]
class = "Subject 4"
teacher = "Teacher 4"
room = "Room 4"

[[tuesday]]
class = "Subject 5"
teacher = "Teacher 5"
room = "Room 5"

[[tuesday]]
class = "Subject 5"
teacher = "Teacher 5"
room = "Room 5"

[[tuesday]]
class = "Subject 6"
teacher = "Teacher 6"
room = "Room 6"

[[tuesday]]
class = "Subject 6"
teacher = "Teacher 6"
room = "Room 6"

[[tuesday]]
class = "Subject 7"
teacher = "Teacher 7"

[[tuesday]]
class = "Subject 7"
teacher = "Teacher 7"

# WEDNESDAY

[[wednesday]]
class = "Subject 8"
teacher = "Teacher 8"
room = "Room 8"

[[wednesday]]
class = "Subject 8"
teacher = "Teacher 8"
room = "Room 8"

[[wednesday]]
class = "Subject 9"
teacher = "Teacher 9"
room = "Room 9"

[[wednesday]]
class = "Subject 9"
teacher = "Teacher 9"
room = "Room 9"

[[wednesday]]
class = "Subject 10"
teacher = "Teacher 10"
room = "Room 10"

[[wednesday]]
class = "Subject 10"
teacher = "Teacher 10"
room = "Room 10"

# THURSDAY

[[thursday]]
class = "Subject 11"
teacher = "Teacher 11"
room = "Room 11"

[[thursday]]
class = "Subject 11"
teacher = "Teacher 11"
room = "Room 11"

[[thursday]]
class = "Subject 12"
teacher = "Teacher 12"
room = "Room 12"

[[thursday]]
class = "Subject 12"
teacher = "Teacher 12"
room = "Room 12"

[[thursday]]
class = "Subject 13"
teacher = "Teacher 13"
room = "Room 13"

[[thursday]]
class = "Subject 13"
teacher = "Teacher 13"
room = "Room 13"

# FRIDAY 🎉

[[friday]]
class = "Subject 14"
teacher = "Teacher 14"
room = "Room 14"

[[friday]]
class = "Subject 14"
teacher = "Teacher 14"
room = "Room 14"

[[friday]]
class = "Subject 15"
teacher = "Teacher 15"
room = "Room 15"

[[friday]]
class = "Subject 15"
teacher = "Teacher 15"
room = "Room 15"

[[friday]]
class = "Subject 16"
teacher = "Teacher 16"
room = "Room 16"

[[friday]]
class = "Subject 16"
teacher = "Teacher 16"
room = "Room 16"
